num1 = input("Enter a number: ")
num2 = input("Enter another number: ")
result1 = (num1) + (num2)
result2 = int(round(float(num1))) + int(round(float(num2)))
result3 = float(num1) + float(num2)
print(result1)
print(result2)
print(result3)
